language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  include:
  - php: 7.2
    env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: 7.4snapshot

before_script:
  - travis_retry composer self-update
  - travis_wait travis_retry composer install ${COMPOSER_FLAGS} --no-ansi --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover=clover.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.composer/cache
